### PR TITLE
Additional validation, messages, and features

### PR DESCRIPTION
**Pull request by neil-sabol**
Validation:
-Checks script is being run as root
-Checks presence of httpd (as installed through yum/rpm)

Messages:
-Added summary and results dialogue

Features:
-Creates new user and home directory for each domain
-Sets permissions
-Sets up SFTP chroot to new user's home directory
-Creates keypair for new user and adds ec2-user's authorized keys by default

### CODE REVIEW

**Comment by neil-sabol** [comment]
Hi Jack,

Sorry about that - it is possible I am doing something wrong. Here is a new pull request.

Let me know how things look on your end.

Thank you and enjoy the evening,
-Neil

**Comment by jamorat** [comment]
Hey Neil, the pull request is in!  Let me ask you something, I was thinking of making a tagged release. Do you think this description is suitable for v1.0 tagged release?  What if anything would you change about it? You are really strong in your ability to document and articulate what is taking place. I would love to know what your eyes envision here:

"Ability to create vhosts, includes validation. Creates vhost as well as user account. AWS specific feature: adds ec2-user key to new account's ssh authorized users folder."

**Comment by neil-sabol** [comment]
Hello Jack,

Apologies for the delay and I hope you had an enjoyable weekend.

Thanks for pulling that in - appreciate it!

I think your description looks good - the only think I might add is a note
about the SFTP only (no shell) access and the SFTP chroot to the site
user's home directory. Not sure if there is a clean way to work all of that
in though.

Maybe something like:

"Ability to create vhosts, includes basic validation. Creates vhost, user
account (sftp only) and sftp chroot to user's home. AWS specific feature:
adds ec2-user key to new account's ssh authorized users folder."

That may be too long though.

I trust your judgement - let me know your thoughts.

Thank you and enjoy the evening,
-Neil

**Comment by jamorat** [comment]
Hey Neil, the tagged version is up!

**Comment by neil-sabol** [comment]
Hi Jack,

Awesome, thank you for doing that!

Have a great week.

Best,
-Neil

**Comment by jamorat** [comment]
Neil my friend... my mind has been rolling this script around for a couple of weeks now. In particular I am contemplating the aspect of accessing the user's key.  What are your thoughts on security implications here? Thanks!

**Comment by neil-sabol** [comment]
Hi Jack,

Hope all is well and that you enjoyed the weekend.

That is a good point. Which aspect of the key sharing are you referring to?
There are 2 things I added that may be questionable:

   - Adding ec2-user's key to newly created accounts
   - Generating and providing the option to display a newly created user's
   new private key

I suspect the latter is more dangerous. The former was just a convenience
for me (instead of juggling many keys, I use the existing ec2-user key to
connect to accounts housing different sites).

Do you think it makes sense to simply generate a new key pair for users
(upon creation) but not provide the option to print it to the console?

Let me know your thoughts. Not sure exactly where I was going with printing
the newly generated private key to the screen anyway - that does not add a
lot of value upon further review.

Thanks and talk soon,

-Neil

**Pull request merged**
