### PR TITLE
Added additional validation/updated readme

### PR DESCRIPTION
**Pull request by neil-sabol**

### CODE REVIEW

**Comment by neil-sabol** [comment]
Sorry for the miss - still learning github workflow. Thanks for sharing your code! -N

**Comment by jamorat** [comment]
Hey Neil! Thanks for sharing your code as well! Really cool to see the better set up notes. Hey one question, what are your thoughts on specifically enforcing 2.4?  I was thinking if we enforce 2.4 - a.) in a few months we will be enforcing an out of date version, and b.) there might be all kinds of reasons that someone doesn't have 2.4 running?  

I was just wondering your thoughts on that and if you might feel some flexibility for simply encouraging the latest, but perhaps not requiring it?  I'm just throwing spaghetti against the wall. Wanted to ping you before doing the pull in. Thanks!

**Comment by neil-sabol** [comment]
Hi Jack,

Thanks for the quick reply and suggestion - you raise an excellent point
regarding the apache version.

Do you think a sanity check like the following would suffice?

rpm -qa | grep httpd
(and check the exit status of that command)

I was being lazy and used httpd24 because rpm -q matched that directly
(without grepping) - I definitely want to incorporate your feedback of not
enforcing a single apache version.

Let me know your thoughts as time permits.

Thank you again for the note and enjoy the evening (or day).

Best,
-Neil

**Comment by jamorat** [comment]
Yea why not do that, and let's get it pulled in!  You're welcome, and thank you for such great communication! This is a reminder to continue work on this. Perhaps we can continue the conversation as time goes on. Have a great night. (I'm in the USA, so it is indeed night.)  :o)

**Comment by neil-sabol** [comment]
Hi Jack,

Awesome, sounds great. Thank you again for the suggestion and guidance.

I submitted a new pull request (I had cancelled the original one) - if
there was an easier way, let me know. I am very new to github and the
workflow.

Let me know what you think of my branch. It introduces some other features
that may not be ideal for all applications (I tailored my adjustments to
some of my own requirements). If you prefer, I can fork the original again
and implement just the validation/install instructions/etc.

It would be awesome to collaborate going forward. I had planned to create
something to the affect of a make-vhost-ssl script (leveraging CertBot and
Let's Encrypt for free certs) at some point.

Thank you again for your time and guidance,
-Neil

**Comment by jamorat** [comment]
It seems the second one got zonked too. Can you please open the pull request with your latest changes again? Thanks!

**Pull request closed without merging**
